import type { ReactNode } from 'react';

// Mirror of packages/design-system/pattern-library/components/layout-agentic-shell.html
// Classes track components.css; do not edit this file's class attribute without
// also editing the pattern-library HTML.
//
// Usage: render the agentic-shell panes as positional children — typically
// nav (left) + panel-splitter + main (center) + panel-splitter + aside (right).
// The shell is pure layout; nested panel-nav / panel-chat / panel-content
// compositions remain inline carve-outs in app code until a second consumer
// needs them. Layout-shell carve-out per ThreePanelShell precedent —
// slotModel: "children-slot", markdocTag: null.

export interface AgenticShellProps {
  children: ReactNode;
  className?: string;
}

export function AgenticShell({ children, className = '' }: AgenticShellProps) {
  const classes = ['agentic-shell', className].filter(Boolean).join(' ');
  return <div className={classes}>{children}</div>;
}
