import type { QueueItemProps, QueueItemSla } from './QueueItem.props';

export type { QueueItemProps, QueueItemSla, QueueItemUrgency } from './QueueItem.props';

// Mirror of packages/design-system/pattern-library/components/queue-item.html
// Classes track components.css; do not edit this file's class attributes without
// also editing the pattern-library HTML.
//
// Usage: render inside a <li> element, which sits inside a <ul className="queue-list">.
// See queue-sidebar.html for the canonical composition.

const slaIcon: Record<QueueItemSla['status'], string> = {
  warning: 'fa-clock',
  breached: 'fa-circle-exclamation',
};

export function QueueItem({
  urgency,
  active = false,
  onClick,
  name,
  category,
  summary,
  time,
  sla,
  className = '',
}: QueueItemProps) {
  const classes = [
    'queue-item',
    `is-${urgency}`,
    active && 'active',
    className,
  ]
    .filter(Boolean)
    .join(' ');

  return (
    <button
      type="button"
      className={classes}
      aria-current={active ? 'true' : undefined}
      onClick={onClick}
    >
      <span className="queue-item-header">
        <span className="queue-item-name">{name}</span>
        <span className="badge badge-sm badge-pill">{category}</span>
      </span>
      <span className="queue-item-summary">{summary}</span>
      <span className="queue-item-meta">
        <span>{time}</span>
        {sla && (
          <span
            className={`queue-item-sla is-${sla.status}`}
            aria-label={sla.label}
          >
            <i className={`fa-solid ${slaIcon[sla.status]}`} aria-hidden="true"></i>{' '}
            {sla.text}
          </span>
        )}
      </span>
    </button>
  );
}
