// Mirror of packages/design-system/pattern-library/components/queue-item.html
// Classes track components.css; do not edit this file's class attributes without
// also editing the pattern-library HTML.

export type QueueItemUrgency = 'urgent' | 'attention' | 'info';

export interface QueueItemSla {
  status: 'warning' | 'breached';
  text: string;
}

export interface QueueItemProps {
  urgency: QueueItemUrgency;
  active?: boolean;
  name: string;
  category: string;
  summary: string;
  time: string;
  sla?: QueueItemSla;
  className?: string;
}

const slaIcon: Record<QueueItemSla['status'], string> = {
  warning: 'fa-clock',
  breached: 'fa-circle-exclamation',
};

export function QueueItem({
  urgency,
  active = false,
  name,
  category,
  summary,
  time,
  sla,
  className = '',
}: QueueItemProps) {
  const classes = [
    'queue-item',
    `is-${urgency}`,
    active && 'active',
    className,
  ]
    .filter(Boolean)
    .join(' ');

  return (
    <div className={classes}>
      <div className="queue-item-header">
        <span className="queue-item-name">{name}</span>
        <span className="badge badge-sm badge-pill">{category}</span>
      </div>
      <div className="queue-item-summary">{summary}</div>
      <div className="queue-item-meta">
        <span>{time}</span>
        {sla && (
          <span className={`queue-item-sla is-${sla.status}`}>
            <i className={`fa-solid ${slaIcon[sla.status]}`}></i> {sla.text}
          </span>
        )}
      </div>
    </div>
  );
}
