import type { ReactNode } from 'react';

// Mirror of packages/design-system/pattern-library/components/queue-section-header.html
// Renders as an <h2> for heading hierarchy within a queue sidebar.
// Classes track components.css; do not edit this file's class attributes without
// also editing the pattern-library HTML.

export type QueueSectionTier = 'urgent' | 'attention' | 'info';

export interface QueueSectionHeaderProps {
  tier: QueueSectionTier;
  children: ReactNode;
  /** Optional id for aria-labelledby from the enclosing <section>. */
  id?: string;
  className?: string;
}

const tierIcon: Record<QueueSectionTier, string> = {
  urgent: 'error',
  attention: 'notifications',
  info: 'info',
};

export function QueueSectionHeader({
  tier,
  children,
  id,
  className = '',
}: QueueSectionHeaderProps) {
  const classes = ['queue-section-header', `is-${tier}`, className]
    .filter(Boolean)
    .join(' ');

  return (
    <h2 id={id} className={classes}>
      <span className="material-symbols-outlined" aria-hidden="true">
        {tierIcon[tier]}
      </span>
      <span>{children}</span>
    </h2>
  );
}
