import type { ReactNode } from 'react';

// Mirror of packages/design-system/pattern-library/components/queue-section-header.html
// Classes track components.css; do not edit this file's class attributes without
// also editing the pattern-library HTML.

export type QueueSectionTier = 'urgent' | 'attention' | 'info';

export interface QueueSectionHeaderProps {
  tier: QueueSectionTier;
  children: ReactNode;
  className?: string;
}

const tierIcon: Record<QueueSectionTier, string> = {
  urgent: 'fa-circle-exclamation',
  attention: 'fa-bell',
  info: 'fa-circle-info',
};

export function QueueSectionHeader({ tier, children, className = '' }: QueueSectionHeaderProps) {
  const classes = ['queue-section-header', `is-${tier}`, className]
    .filter(Boolean)
    .join(' ');

  return (
    <div className={classes}>
      <i className={`fa-solid ${tierIcon[tier]}`}></i>
      <span>{children}</span>
    </div>
  );
}
