import type { ThreadMessageHumanProps } from './ThreadMessageHuman.props';

export type { ThreadMessageHumanProps } from './ThreadMessageHuman.props';

// Mirror of packages/design-system/pattern-library/components/thread-msg-human.html
// Classes track components.css; do not edit this file's class attributes without
// also editing the pattern-library HTML.

export function ThreadMessageHuman({
  author,
  children,
  time,
  className = '',
}: ThreadMessageHumanProps) {
  const classes = ['thread-msg-human', className].filter(Boolean).join(' ');
  return (
    <div className={classes}>
      <span className="thread-msg-human-label">{author}</span>
      <div className="thread-msg-human-bubble">{children}</div>
      <span className="thread-msg-time mt-0.5">{time}</span>
    </div>
  );
}
