import type { ReactNode } from 'react';

// Mirror of packages/design-system/pattern-library/components/three-panel-shell.html
// Classes track components.css; do not edit this file's class attributes without
// also editing the pattern-library HTML.
//
// Usage: render three direct children in order — left aside, center <main>,
// right aside. The shell is pure layout; it enforces no semantics on its
// children beyond their placement in the flex row.

export interface ThreePanelShellProps {
  children: ReactNode;
  className?: string;
}

export function ThreePanelShell({ children, className = '' }: ThreePanelShellProps) {
  const classes = ['three-panel-shell', className].filter(Boolean).join(' ');
  return <div className={classes}>{children}</div>;
}
