import { useId } from 'react';
import type {
  ThreadMessageResponseProps,
  ThreadMessageResponseOutcome,
} from './ThreadMessageResponse.props';

export type {
  ThreadMessageResponseProps,
  ThreadMessageResponseOutcome,
} from './ThreadMessageResponse.props';

// Mirror of packages/design-system/pattern-library/components/thread-msg-response.html
// Classes track components.css; do not edit this file's class attributes without
// also editing the pattern-library HTML.
//
// useId() is required by Preline HSCollapse — see ThreadMessageToolCall for context.

const outcomeIcon: Record<ThreadMessageResponseOutcome, string> = {
  approved: 'fa-circle-check',
  rejected: 'fa-circle-xmark',
};

export function ThreadMessageResponse({
  outcome,
  toggleContent,
  children,
  id,
  defaultExpanded = false,
  className = '',
}: ThreadMessageResponseProps) {
  const generatedId = useId();
  const detailId = id ?? `response-detail-${generatedId.replace(/:/g, '')}`;
  const classes = [
    'thread-msg-response',
    `is-${outcome}`,
    className,
  ]
    .filter(Boolean)
    .join(' ');
  const detailClass = ['hs-collapse', defaultExpanded ? '' : 'hidden', 'thread-msg-response-detail']
    .filter(Boolean)
    .join(' ');

  return (
    <div className={classes}>
      <button
        type="button"
        className="thread-msg-response-toggle hs-collapse-toggle"
        data-hs-collapse={`#${detailId}`}
        aria-expanded={defaultExpanded}
        aria-controls={detailId}
      >
        <i className={`fa-solid ${outcomeIcon[outcome]}`} aria-hidden="true"></i>
        <span>{toggleContent}</span>
      </button>
      <div id={detailId} className={detailClass}>
        {children}
      </div>
    </div>
  );
}
