import type { ReactNode } from 'react';

// Mirror of packages/design-system/pattern-library/components/three-panel-shell.html
// Classes track components.css; do not edit this file's class attributes without
// also editing the pattern-library HTML.
//
// Usage: render three direct children in order — left aside, center <main>,
// right aside. The shell is pure layout; it enforces no semantics on its
// children beyond their placement in the flex row. The outer `.app-shell`
// div supplies the Haven floating-page envelope (sand-50 page bg shows
// around it via padding); the inner `.three-panel-shell` carries the 3px
// sand-150 border + border-radius-md that makes the app float inside its frame.
//
// Composition note: this component accepts children: ReactNode. Layout-shell
// carve-out — it composes other registered components (QueueSidebar, ThreadPanel,
// etc.) by position, not by typed named-slots. Registered in registry.json with
// slotModel: "children-slot" + markdocTag: null so it is not Markdoc-addressable.

export interface ThreePanelShellProps {
  children: ReactNode;
  className?: string;
}

export function ThreePanelShell({ children, className = '' }: ThreePanelShellProps) {
  const shellClasses = ['three-panel-shell', className].filter(Boolean).join(' ');
  return (
    <div className="app-shell">
      <div className={shellClasses}>{children}</div>
    </div>
  );
}
