import { useId } from 'react';
import type { ThreadMessageToolCallProps } from './ThreadMessageToolCall.props';

export type { ThreadMessageToolCallProps } from './ThreadMessageToolCall.props';

// Mirror of packages/design-system/pattern-library/components/thread-msg-tool-call.html
// Classes track components.css; do not edit this file's class attributes without
// also editing the pattern-library HTML.
//
// useId() is required by Preline HSCollapse: the toggle and the detail panel
// must reference each other via stable, page-unique ids. This is the
// porter-skill carve-out for "imported hook required by Preline initialization."

export function ThreadMessageToolCall({
  toolName,
  resultSummary,
  time,
  children,
  id,
  defaultExpanded = false,
  className = '',
}: ThreadMessageToolCallProps) {
  const generatedId = useId();
  const detailId = id ?? `tool-detail-${generatedId.replace(/:/g, '')}`;
  const toggleId = `${detailId}-toggle`;
  const classes = ['thread-msg-tool', className].filter(Boolean).join(' ');
  const detailClass = ['hs-collapse', defaultExpanded ? '' : 'hidden', 'thread-msg-tool-detail']
    .filter(Boolean)
    .join(' ');

  return (
    <div className={classes}>
      <div className="thread-msg-tool-icon">
        <i className="fa-solid fa-bolt" aria-hidden="true"></i>
      </div>
      <div className="thread-msg-tool-content">
        <button
          type="button"
          className="hs-collapse-toggle thread-msg-tool-toggle"
          id={toggleId}
          aria-expanded={defaultExpanded}
          aria-controls={detailId}
          data-hs-collapse={`#${detailId}`}
        >
          <span className="thread-msg-tool-name">{toolName}</span>
          <span className="thread-msg-tool-result">{resultSummary}</span>
          <span className="thread-msg-time ml-1">{time}</span>
        </button>
        <div id={detailId} className={detailClass}>
          {children}
        </div>
      </div>
    </div>
  );
}
