import type { ThreadMessageSystemProps } from './ThreadMessageSystem.props';

export type { ThreadMessageSystemProps } from './ThreadMessageSystem.props';

// Mirror of packages/design-system/pattern-library/components/thread-msg-system.html
// Classes track components.css; do not edit this file's class attributes without
// also editing the pattern-library HTML.

export function ThreadMessageSystem({
  text,
  time,
  className = '',
}: ThreadMessageSystemProps) {
  const classes = ['thread-msg-system', className].filter(Boolean).join(' ');
  return (
    <div className={classes}>
      <span>{text}</span>
      <span className="thread-msg-time">{time}</span>
    </div>
  );
}
