import { createElement, useId } from 'react';
import type { ThreadApprovalCardProps } from './ThreadApprovalCard.props';

export type {
  ThreadApprovalCardProps,
  ThreadApprovalCardVariant,
  ThreadApprovalAttachment,
  ThreadApprovalEffects,
  ThreadApprovalNoteMode,
} from './ThreadApprovalCard.props';

// Mirror of packages/design-system/pattern-library/components/thread-approval-card.html
// Classes track components.css; do not edit this file's class attributes without
// also editing the pattern-library HTML.
//
// THE HERO COMPONENT. Iterate pass 2026-04-24 added:
//   - root <section role="region" aria-labelledby> + <h{headingLevel}> title
//     (a11y review #1, #2 — landmark + heading semantics)
//   - sr-only <label> for the textarea (a11y review #3 — placeholder is not a label)
//   - aria-labelledby wiring effects label → <ul> (a11y review #4)
//   - noteMode + noteRef + noteInvalid API for parent-controlled reject flow
//     (a11y review #5, IA review #1)
//   - attachment.viewed warning state (IA review #3 — silent-failure prevention)

const variantClass: Record<NonNullable<ThreadApprovalCardProps['variant']>, string> = {
  standard: '',
  urgent: 'is-urgent',
  warning: 'is-warning',
  historical: 'is-historical',
};

export function ThreadApprovalCard({
  variant = 'standard',
  icon = 'fa-hand',
  title,
  headingLevel = 3,
  contextTitle,
  contextMeta,
  summary,
  effects,
  attachment,
  actions,
  noteMode = 'hidden',
  noteLabel = 'Approval note',
  notePlaceholder = 'Add a note (optional)',
  noteRows = 2,
  noteValue,
  onNoteChange,
  noteRef,
  noteInvalid = false,
  className = '',
}: ThreadApprovalCardProps) {
  const reactId = useId();
  const titleId = `approval-title-${reactId.replace(/:/g, '')}`;
  const effectsLabelId = `approval-effects-label-${reactId.replace(/:/g, '')}`;
  const noteId = `approval-note-${reactId.replace(/:/g, '')}`;

  const classes = ['thread-approval-card', variantClass[variant], className]
    .filter(Boolean)
    .join(' ');

  const attachmentClasses = ['thread-approval-attachment'];
  if (attachment && attachment.viewed === false) {
    attachmentClasses.push('thread-approval-attachment-unviewed');
  }
  const attachmentIcon =
    attachment && attachment.viewed === false ? 'fa-circle-exclamation' : 'fa-paperclip';

  const heading = createElement(
    `h${headingLevel}`,
    { id: titleId },
    title,
  );

  return (
    <section className={classes} role="region" aria-labelledby={titleId}>
      <div className="thread-approval-header">
        <i className={`fa-solid ${icon}`} aria-hidden="true"></i>
        {heading}
      </div>
      <div className="thread-approval-body">
        <div className="thread-approval-context">
          <span className="thread-approval-context-title">{contextTitle}</span>
          <span className="thread-approval-context-meta">{contextMeta}</span>
        </div>
        {summary && <div className="thread-approval-summary">{summary}</div>}
        {effects && (
          <div className="thread-approval-effects">
            <span className="thread-approval-effects-label" id={effectsLabelId}>
              {effects.label}
            </span>
            <ul aria-labelledby={effectsLabelId}>
              {effects.items.map((item, i) => (
                <li key={i}>{item}</li>
              ))}
            </ul>
          </div>
        )}
        {attachment && (
          <div className={attachmentClasses.join(' ')}>
            <i className={`fa-solid ${attachmentIcon}`} aria-hidden="true"></i>
            <span>{attachment.label}</span>
            {attachment.viewHref ? (
              <a
                href={attachment.viewHref}
                onClick={attachment.onView}
                className="text-link text-xs"
              >
                {attachment.viewLabel}
              </a>
            ) : attachment.onView ? (
              <button
                type="button"
                onClick={attachment.onView}
                className="text-link text-xs"
              >
                {attachment.viewLabel}
              </button>
            ) : null}
          </div>
        )}
      </div>
      {actions && <div className="thread-approval-actions">{actions}</div>}
      {noteMode !== 'hidden' && (
        <div className="thread-approval-note">
          <label htmlFor={noteId} className="thread-approval-note-label sr-only">
            {noteLabel}
          </label>
          <textarea
            id={noteId}
            ref={noteRef}
            rows={noteRows}
            placeholder={notePlaceholder}
            value={noteValue}
            onChange={(e) => onNoteChange?.(e.target.value)}
            aria-required={noteMode === 'required' ? true : undefined}
            aria-invalid={noteInvalid || undefined}
          />
        </div>
      )}
    </section>
  );
}
