// ============================================================================
// EMIT CORE — DS-agnostic. Consumes a binding (the seam) + a surface config
// (content + chrome) and emits self-contained static HTML. One engine; the
// three prior emitters (doc-emit / SoT pandoc / reasoning hand-built) become
// configs of this. Per ~/.claude/plans/surface-emission-convergence.md.
//
//   SURFACE=docs | sot   (default docs)
//   MODE=devserver | standalone  (default devserver)
// ============================================================================

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { unified } from 'unified';
import remarkParse from 'remark-parse';
import remarkGfm from 'remark-gfm';
import remarkDirective from 'remark-directive';
import remarkRehype from 'remark-rehype';
import rehypeStringify from 'rehype-stringify';
import matter from 'gray-matter';

import { havenBinding } from './handlers.mjs';
import { renderPage } from './shell.mjs';
import { generateSotContent } from './sot-gen.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const MODE = process.env.MODE === 'standalone' ? 'standalone' : 'devserver';
const SURFACE = process.env.SURFACE || 'docs';

// Build the processor from the BINDING (DS-agnostic core; haven-specific plugins
// come from the binding). Swap the binding -> a different design system.
const processor = unified()
  .use(remarkParse)
  .use(remarkGfm)
  .use(remarkDirective);
for (const p of havenBinding.remarkPlugins) processor.use(p);
processor.use(remarkRehype, { allowDangerousHtml: true });
for (const p of havenBinding.rehypePlugins) processor.use(p);
processor.use(rehypeStringify, { allowDangerousHtml: true });

function renderMarkdown(md, { stripH1 = false } = {}) {
  let { content, data } = matter(md);
  // Sidebar chrome renders the page title in its own header, so a leading body
  // H1 would duplicate it. Strip a single leading "# Title" line in that mode.
  if (stripH1) content = content.replace(/^\s*#\s+.*\r?\n/, '');
  return { html: processor.processSync(content).toString(), frontmatter: data };
}

// ---- surface configs (each = a consumer; zero bespoke emitter code) --------
const CENA_ROOT = '/Users/aaronsleeper/Vaults/Knowledge/Projects/Cena Health';
const SOT_REPO = `${CENA_ROOT}/Partners/UCONN Health`;
const SURFACES = {
  docs: {
    chrome: 'sidebar',
    manifest: JSON.parse(readFileSync(resolve(__dirname, 'nav.json'), 'utf8')),
    pages: null, // derived from manifest below
    contentDir: resolve(__dirname, 'content'),
    devOut: resolve(__dirname, '../../packages/design-system/pattern-library/_docs-spike'),
    standaloneOut: resolve(__dirname, 'dist'),
  },
  // FULL INTERNAL DOCUMENTATION SITE — the Confluence+Jira-lite home for the
  // UConn pilot (internal audience: Aaron/Vanessa/Andrey). Sidebar nav over the
  // canonical markdown + derived cap/meeting indexes (sot-gen.mjs). define-once:
  // the Jira half (ledger/critical-path/what-we-need) stays in SoT.md; the nav's
  // "Work & state" group deep-links to its section anchors. IA: ~/.claude/plans/
  // uconn-sot-site/ia-proposal.md. Auth/hosting PARKED (do not flip Blaze).
  sot: {
    chrome: 'sidebar',
    manifest: JSON.parse(readFileSync(resolve(__dirname, 'nav-sot.json'), 'utf8')),
    contentDir: resolve(__dirname, 'content-sot'),
    pages: [
      // ── Org level (the durable parent frame — thin by design) ──────────────
      { slug: 'index' },             // authored org landing (content-sot/index.md)
      { slug: 'programs' },          // authored program registry (UConn = entry 1)
      { slug: 'governance', srcAbs: `${CENA_ROOT}/current-facts.md`, title: 'Governance & compliance' },
      { slug: 'org-capabilities' },  // authored stub (promotion layer)
      { slug: 'sops' },              // generated by sot-gen (derived from the 2 SOP docs)
      // ── UConn pilot (the child program space — the real depth) ─────────────
      { slug: 'uconn', srcAbs: `${SOT_REPO}/UConn Pilot — Source of Truth.md`, title: 'UConn pilot — where things stand' },
      { slug: 'uconn-patient-journey', srcAbs: `${SOT_REPO}/Patient Journey — capabilities by stage.md`, title: 'Patient journey' },
      { slug: 'uconn-timeline', srcAbs: `${SOT_REPO}/Launch Timeline — Inference & Gates.md`, title: 'Launch timeline & gates' },
      { slug: 'uconn-apps' },         // generated by sot-gen (derived dev cap-index)
      { slug: 'uconn-operations' },   // generated by sot-gen (derived ops cap-index)
      { slug: 'uconn-evidence' },     // authored stub (content-sot/)
      { slug: 'uconn-compliance' },   // authored pointer (program compliance)
      { slug: 'uconn-contract' },     // authored pointer page (content-sot/)
      { slug: 'uconn-reasoning', srcAbs: resolve(__dirname, 'content-reason/index.md'), title: 'Why it works this way' },
      { slug: 'uconn-decisions', srcAbs: `${SOT_REPO}/2026-05-26 Tech Talk — action items.md`, title: 'Decision log' },
      { slug: 'uconn-workflow-mapping-2026-06-02' }, // authored session-prep asset (content-sot/)
      { slug: 'uconn-meetings' },     // generated index of the dated meeting notes
    ],
    devOut: resolve(__dirname, '../../packages/design-system/pattern-library/_sot-spike'),
    standaloneOut: resolve(__dirname, '../../handoff/cena-sot'),
  },
  // The cena-reasoning surface re-expressed as a CONSUMER of the engine (was
  // hand-built HTML). Proof that the third emitter folds in too. Content slice
  // is representative (full transcription is mechanical remaining work).
  reason: {
    chrome: 'surface',
    manifest: { title: 'Cena — Reasoning Surface' },
    chromeConfig: {
      banner: '<strong>Patient-app reasoning.</strong> A surface that shows the thinking and makes each decision pokeable — open the disclosures, push where it’s soft. A <em>view</em> of the real plans, generated, not hand-built.',
      nav: [],
    },
    pages: [{ slug: 'index', title: 'Reasoning Surface' }],
    contentDir: resolve(__dirname, 'content-reason'),
    devOut: resolve(__dirname, '../../packages/design-system/pattern-library/_reason-spike'),
    standaloneOut: resolve(__dirname, '../../handoff/cena-reasoning'),
  },
};

const cfg = SURFACES[SURFACE];
if (!cfg) { console.error(`unknown SURFACE=${SURFACE}`); process.exit(1); }

// SoT surface: regenerate the derived cap/meeting indexes, then append the
// per-meeting-note pages (emitted but kept out of the sidebar — linked from the
// Meeting notes index page instead).
if (SURFACE === 'sot') {
  const notes = generateSotContent({ repo: SOT_REPO, cenaRoot: CENA_ROOT, contentDir: cfg.contentDir });
  cfg.pages.push(...notes.map((n) => ({ slug: n.slug, srcAbs: n.srcAbs, title: n.title })));
}

const pages = cfg.pages || cfg.manifest.nav.flatMap((g) => g.pages);
// OUT_DIR env overrides the per-surface default — used by the live SoT build.sh
// to emit straight into the uconn-pilot-docs surface/ dir.
const OUT_DIR = process.env.OUT_DIR
  ? resolve(process.env.OUT_DIR)
  : MODE === 'standalone' ? cfg.standaloneOut : cfg.devOut;
mkdirSync(OUT_DIR, { recursive: true });

for (const page of pages) {
  const src = page.srcAbs || resolve(cfg.contentDir, `${page.slug}.md`);
  const md = readFileSync(src, 'utf8');
  const { html, frontmatter } = renderMarkdown(md, { stripH1: cfg.chrome === 'sidebar' });
  const out = renderPage({
    chrome: cfg.chrome,
    chromeConfig: cfg.chromeConfig,
    manifest: cfg.manifest,
    slug: page.slug,
    title: frontmatter.title || page.title,
    description: frontmatter.description,
    bodyHtml: html,
    mode: MODE,
    proseCss: havenBinding.proseCss,
  });
  writeFileSync(resolve(OUT_DIR, `${page.slug}.html`), out, 'utf8');
  console.log(`  emitted  ${SURFACE}/${page.slug}.html  (${MODE}; ${html.length} bytes body)`);
}
console.log(`\nEmitted ${pages.length} page(s) [surface=${SURFACE}] -> ${OUT_DIR}`);
