import type { ViteDevServer, Connect } from 'vite';
import { readFile, writeFile, readdir, mkdir, stat } from 'node:fs/promises';
import { resolve, dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { IncomingMessage, ServerResponse } from 'node:http';

const __dirname = dirname(fileURLToPath(import.meta.url));

// Target paths — split between the repo (authored source) and the Obsidian
// install dir (runtime artifacts the renderer actually reads).
//
//   REPO_DIR    — Lab/haven-obsidian-theme/      presets/*.json live here
//   INSTALL_DIR — Vaults/.obsidian/themes/Haven/ Obsidian loads CSS from here
//
// Path-E architecture (2026-06-07): Obsidian's theme loader does NOT follow
// @import chains for hot-reload — verified by lime-green test failing both
// with and without theme toggle. So theme.css can't be a 2-line loader; it
// must contain the full CSS Obsidian reads.
//
// Composition rule: theme.css = theme.compiled.css + theme.editor-overrides.css,
// composed deterministically by whichever machine writer ran last. The two
// writers are:
//   - build.mjs        → owns theme.compiled.css; also writes theme.css when run
//   - this middleware  → owns theme.editor-overrides.css; also writes theme.css on
//                        every editor save
// Neither hand-edits; both compose from versioned source (src/*.css for build,
// presets/*.json for editor). The rule "Never hand-edit theme.css" still binds
// human contributors — machines compose, humans don't.
//
// theme.compiled.css is read into memory on middleware startup; running
// `node build.mjs` requires restarting the editor (acceptable Phase 1).
const PKG_ROOT = __dirname;
const REPO_DIR = resolve(PKG_ROOT, '../../../haven-obsidian-theme');
const INSTALL_DIR = '/Users/aaronsleeper/Vaults/.obsidian/themes/Haven';
const THEME_CSS = join(INSTALL_DIR, 'theme.css');
const THEME_COMPILED = join(INSTALL_DIR, 'theme.compiled.css');
const THEME_OVERRIDES = join(INSTALL_DIR, 'theme.editor-overrides.css');
const PRESETS_DIR = join(REPO_DIR, 'presets');

let compiledCache: string | null = null;
async function loadCompiled(): Promise<string> {
  if (compiledCache !== null) return compiledCache;
  compiledCache = await readFile(THEME_COMPILED, 'utf8');
  return compiledCache;
}

async function readBody(req: IncomingMessage): Promise<string> {
  return new Promise((res, rej) => {
    const chunks: Buffer[] = [];
    req.on('data', (c) => chunks.push(c));
    req.on('end', () => res(Buffer.concat(chunks).toString('utf8')));
    req.on('error', rej);
  });
}

function json(res: ServerResponse, status: number, body: unknown) {
  res.statusCode = status;
  res.setHeader('content-type', 'application/json');
  res.end(JSON.stringify(body));
}

function text(res: ServerResponse, status: number, body: string) {
  res.statusCode = status;
  res.setHeader('content-type', 'text/plain');
  res.end(body);
}

async function ensurePresetsDir() {
  try {
    await stat(PRESETS_DIR);
  } catch {
    await mkdir(PRESETS_DIR, { recursive: true });
  }
}

function safePresetName(name: string): string | null {
  // Allow lowercase letters, numbers, dashes only — defends against path traversal.
  if (!/^[a-z0-9][a-z0-9-]{0,63}$/.test(name)) return null;
  return name;
}

const OVERRIDES_HEADER = `/* ==========================================================================
   theme.editor-overrides.css — record of the editor's last emitted output

   Authored by @haven/theme-editor — DO NOT HAND-EDIT.
   This file is a *record* of what the editor wrote; the runtime theme.css
   composes this content with theme.compiled.css. Modifying this file by hand
   has no effect — the next editor save overwrites it; the next build composes
   theme.css without it.
   ========================================================================== */
`;

const THEME_CSS_HEADER = `/* ==========================================================================
   theme.css — runtime composition of theme.compiled.css + editor overrides

   Generated by either build.mjs or @haven/theme-editor; whichever ran last.
   DO NOT HAND-EDIT — any change is overwritten on the next build or editor save.

   Composition: theme.compiled.css contents, followed by the editor's overrides
   (which win via cascade order for any variable they set).
   ========================================================================== */
`;

export function themeEditorMiddleware(server: ViteDevServer) {
  const handler: Connect.NextHandleFunction = async (req, res, next) => {
    const url = req.url ?? '';
    if (!url.startsWith('/api/')) return next();

    try {
      // GET /api/target — info about the target theme repo
      if (req.method === 'GET' && url === '/api/target') {
        return json(res, 200, {
          themeCss: THEME_CSS,
          overridesCss: THEME_OVERRIDES,
          presetsDir: PRESETS_DIR,
        });
      }

      // GET /api/presets — list preset names
      if (req.method === 'GET' && url === '/api/presets') {
        await ensurePresetsDir();
        const entries = await readdir(PRESETS_DIR);
        const names = entries
          .filter((f) => f.endsWith('.json'))
          .map((f) => f.replace(/\.json$/, ''))
          .sort();
        return json(res, 200, { presets: names });
      }

      // GET /api/presets/:name — load one preset
      const getPresetMatch = url.match(/^\/api\/presets\/([^/]+)$/);
      if (req.method === 'GET' && getPresetMatch) {
        const name = safePresetName(getPresetMatch[1]);
        if (!name) return json(res, 400, { error: 'invalid preset name' });
        try {
          const raw = await readFile(join(PRESETS_DIR, `${name}.json`), 'utf8');
          return json(res, 200, JSON.parse(raw));
        } catch (e: unknown) {
          if ((e as NodeJS.ErrnoException).code === 'ENOENT') {
            return json(res, 404, { error: 'preset not found' });
          }
          throw e;
        }
      }

      // PUT /api/presets/:name — save one preset
      if (req.method === 'PUT' && getPresetMatch) {
        const name = safePresetName(getPresetMatch[1]);
        if (!name) return json(res, 400, { error: 'invalid preset name' });
        const body = await readBody(req);
        // Validate parses as JSON.
        try {
          JSON.parse(body);
        } catch {
          return json(res, 400, { error: 'body is not valid JSON' });
        }
        await ensurePresetsDir();
        await writeFile(join(PRESETS_DIR, `${name}.json`), body, 'utf8');
        return json(res, 200, { ok: true, written: `${name}.json` });
      }

      // POST /api/theme — write the editor's CSS as overrides AND compose
      // it into the runtime theme.css that Obsidian actually loads.
      // Body: text/css string (the editor's generated CSS, no fences).
      if (req.method === 'POST' && url === '/api/theme') {
        const css = await readBody(req);
        const overridesBody = OVERRIDES_HEADER + '\n' + css + '\n';
        // 1. Write the editor's record of its output.
        await writeFile(THEME_OVERRIDES, overridesBody, 'utf8');
        // 2. Compose runtime theme.css = header + compiled + overrides.
        const compiled = await loadCompiled();
        const themeCssBody =
          THEME_CSS_HEADER +
          '\n' +
          compiled.trimEnd() +
          '\n\n' +
          overridesBody.trimEnd() +
          '\n';
        await writeFile(THEME_CSS, themeCssBody, 'utf8');
        return text(res, 200, 'ok');
      }

      return json(res, 404, { error: 'unknown api route' });
    } catch (e: unknown) {
      const msg = e instanceof Error ? e.message : String(e);
      return json(res, 500, { error: msg });
    }
  };
  server.middlewares.use(handler);
}
