/**
 * Obsidian theme.css emitter — Phase 3.
 *
 * Walks the canonical relation registry (RELATION_REGISTRY) and for each
 * registered Obsidian CSS variable, resolves the relation against the
 * current preset + mode and writes the result. Designer-authored overrides
 * in preset.relations replace the registry's expression at resolution time;
 * locks freeze the resolved value at lock-time.
 *
 * Phase 2's per-anchor hardcoded var list is gone — coverage is entirely
 * driven by the registry. Type-face vars (font families) are still emitted
 * directly because they aren't relation-typed; everything else flows
 * through the registry walk.
 */

import type {
  Preset,
  ModeKey,
  TypeFaceValue,
  Relation,
} from './types';
import { valueForMode } from './types';
import { resolveColorRelation, resolveNonColorRelation, isColorRelation } from './relations';
import { REGISTERED_RELATIONS } from './relation-registry';

const MODE_SELECTOR: Record<ModeKey, string> = {
  light: '.theme-light',
  dark: '.theme-dark',
};

// ---------------------------------------------------------------------------
// Relation resolution — with override + lock support
// ---------------------------------------------------------------------------

function resolveRegisteredVar(
  cssVar: string,
  defaultExpr: Relation,
  preset: Preset,
  mode: ModeKey,
): string {
  const override = preset.relations?.[cssVar];

  // Lock wins regardless of override expression — frozen value emits verbatim.
  if (override && (override.kind === 'lock' || override.kind === 'override+lock')) {
    return override.frozenValue;
  }

  // Designer-authored override expression replaces the registry default.
  const expr = override?.kind === 'override' ? override.expr : defaultExpr;

  if (isColorRelation(expr)) {
    return resolveColorRelation(expr, preset, mode);
  }
  const numeric = resolveNonColorRelation(expr, preset, mode);
  // Non-color vars are px-valued dimensions; emit with `px` suffix.
  return `${roundDim(numeric)}px`;
}

function roundDim(n: number): number {
  // Round to 2 decimals to keep emitted CSS tidy.
  return Math.round(n * 100) / 100;
}

// ---------------------------------------------------------------------------
// Type-face vars — emitted directly (not relation-typed)
// ---------------------------------------------------------------------------

function quoteFont(value: TypeFaceValue): string {
  return /^[A-Za-z_][A-Za-z0-9_-]*$/.test(value.family)
    ? value.family
    : `'${value.family.replace(/'/g, "\\'")}'`;
}

function emitTypeFaceVars(preset: Preset, mode: ModeKey): string[] {
  const display = quoteFont(valueForMode(preset.anchors.displayFace, mode));
  const reading = quoteFont(valueForMode(preset.anchors.readingFace, mode));
  return [
    `  --font-display-theme: ${display};`,
    `  --h1-font: ${display};`,
    `  --h2-font: ${display};`,
    `  --h3-font: ${display};`,
    `  --font-text-theme: ${reading};`,
    `  --font-interface-theme: ${reading};`,
    `  --h4-font: ${reading};`,
    `  --h5-font: ${reading};`,
    `  --h6-font: ${reading};`,
  ];
}

// ---------------------------------------------------------------------------
// Per-mode block builder
// ---------------------------------------------------------------------------

function buildModeBlock(preset: Preset, mode: ModeKey): string {
  const lines: string[] = [];

  for (const entry of REGISTERED_RELATIONS) {
    try {
      const value = resolveRegisteredVar(entry.cssVar, entry.expr, preset, mode);
      lines.push(`  ${entry.cssVar}: ${value};`);
    } catch (e) {
      // Resolution failure for one var must not poison the whole block.
      const msg = e instanceof Error ? e.message : String(e);
      lines.push(`  /* ${entry.cssVar}: resolve error — ${msg} */`);
    }
  }

  lines.push('', '  /* Type faces */');
  lines.push(...emitTypeFaceVars(preset, mode));

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Top-level emit
// ---------------------------------------------------------------------------

export function emitObsidian(preset: Preset): string {
  const out: string[] = [];
  out.push(`/* Generated by @haven/theme-editor — preset: ${preset.meta.name} */`);
  out.push(`/* Phase 3 — ${REGISTERED_RELATIONS.length} canonical relations + type-face vars per mode */`);
  for (const mode of ['light', 'dark'] as ModeKey[]) {
    out.push('');
    out.push(`${MODE_SELECTOR[mode]} {`);
    out.push(buildModeBlock(preset, mode));
    out.push('}');
  }
  return out.join('\n');
}
