/**
 * Obsidian theme.css emitter — Phase 1.
 *
 * Produces the CSS block content (without BEGIN/END fences — the middleware
 * adds those) that the editor injects into haven-obsidian-theme/theme.css.
 *
 * v0 scope: ONE anchor (Surface) → two variables (--background-primary,
 * --background-secondary), one rule per mode. Phase 2 expands to all 11
 * anchors and the variable map per UX proposal §1.
 */

import type { Preset, ModeKey, AnchorModeValue } from './types';
import { resolveStop } from './color';

const MODE_SELECTOR: Record<ModeKey, string> = {
  light: '.theme-light',
  dark: '.theme-dark',
};

function emitSurfaceVars(value: AnchorModeValue): string {
  const resolved = resolveStop(value.family, value.stop);
  // Phase 1: only --background-primary + --background-secondary.
  // --background-secondary nudged one stop lighter for the soft step (Phase 2
  // replaces this with the sib() operator).
  const altPos = Math.min(100, value.stop + 10);
  const alt = resolveStop(value.family, altPos);
  return `  --background-primary: ${resolved.hex};\n  --background-secondary: ${alt.hex};`;
}

export function emitObsidian(preset: Preset): string {
  const lines: string[] = [];
  lines.push(`/* Generated by @haven/theme-editor — preset: ${preset.meta.name} */`);

  const surface = preset.anchors.surface;
  if (!surface) {
    lines.push('/* no surface anchor set */');
    return lines.join('\n');
  }

  for (const mode of ['light', 'dark'] as ModeKey[]) {
    const value = surface.modes[mode];
    if (!value) continue;
    lines.push('');
    lines.push(`${MODE_SELECTOR[mode]} {`);
    lines.push(emitSurfaceVars(value));
    lines.push('}');
  }

  return lines.join('\n');
}
